name: dragongym
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^0.8.7+4
  path_provider: ^2.1.2
  path: ^1.9.0

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  http: any
  intl: ^0.18.1
  provider: ^6.0.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.14.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.1
flutter_native_splash:
  color: "#000000"
  image: assets/dragon.png
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo.jpg"
  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/dragonLogoSn.png
    - assets/logo.jpg